language: node_js
node_js:
  - "0.12"

sudo: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel
  - npm install grunt-cli -g

addons:
  apt:
    packages:
      - gcc
