language: node_js
node_js:
  - "0.12"

sudo: false

before_install:
  - npm install grunt-cli -g

addons:
  apt:
    sources:
      - mono
      - mono-libtiff-compat
    packages:
      - gcc
      - mono-devel 
      - referenceassemblies-pcl
      - nunit
